services:
  cleanshop71restapi:
    image: ${DOCKER_REGISTRY-}cleanshop71restapi
    build:
      context: .
      dockerfile: CleanShop 71 RestApi/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - cleanshop71restapi-network

networks:
    cleanshop71restapi-network:
        driver: bridge
